services:
  - name: flask
    type: web
    env: python
    plan: starter
    buildCommand: pip install -r /app/requirements.txt
    startCommand: python main.py
    envVars:
      - file: .env
    dockerfilePath: /app/flask_app/Dockerfile
    autoDeploy: true

  - name: chunker
    type: web
    env: python
    plan: starter
    buildCommand: pip install -r /app/requirements.txt
    startCommand: python chunker.py
    envVars:
      - file: .env
    dockerfilePath: /app/chunker/Dockerfile
    autoDeploy: true

  - name: analyser
    type: web
    env: python
    plan: starter
    buildCommand: pip install -r /app/requirements.txt
    startCommand: python analyser.py
    envVars:
      - file: .env
    dockerfilePath: /app/analyser/Dockerfile
    autoDeploy: true

  - name: plotter
    type: web
    env: python
    plan: starter
    buildCommand: pip install -r /app/requirements.txt
    startCommand: python plotter.py
    envVars:
      - file: .env
    dockerfilePath: /app/plotter/Dockerfile
    autoDeploy: true

  - name: frontend
    type: web
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run serve
    envVars:
      - file: .env
    dockerfilePath: /app/frontend/Dockerfile
    autoDeploy: true

volumes:
  - name: flask-app
  - name: chunker-app
  - name: analyser-app
  - name: plotter-app
  - name: frontend-app
